create table autoii(
id INT GENERATED by DEFAULT as IDENTITY(START WITH 311422030 INCREMENT BY 1),
name VARCHAR(30),
age NUMBER,
PRIMARY KEY(id)

);
drop table autoii;
desc autoii;
insert into autoii(name,age) values('Pokesh',23);
SELECT * FROM autoii;

commit

