create table dateofbirth(
id int generated by default as IDENTITY,
PRIMARY key(id),
name varchar(40),
DateOfBirth DATE default sysdate
);

insert into dateofbirth(name,DateOfBirth)values('Puliii','30-12-2008');

select * from DateOfBirth;
select name,to_char(to_date(DateOfBirth),'DD') as BirthDay from dateofbirth;
select name,to_char(to_date(DateOfBirth),'MM') as BirthDay from dateofbirth;
select name,to_char(to_date(DateOfBirth),'YYYY') as BirthDay from dateofbirth;
select name,to_char(to_date(DateOfBirth),'Day') as BirthDay from dateofbirth;
select name,to_char(to_date(DateOfBirth),'month') as BirthDay from dateofbirth;
select name,to_char(to_date(DateOfBirth),'Year') as BirthDay from dateofbirth;

select Extract(Day from to_Date(DateOfBirth)) as Day from dateofbirth where mod(id,2)=0;


--New Table For Employee
create table WorkersOfMyCompany(
wId int generated by default as identity,
wName varchar(40),
WJoinDate date default sysdate,
wSalary number(10)
);

desc WorkersOfMyCompany;
select * from WorkersOfMyCompany;

alter table WorkersOfMyCompany rename COLUMN Wid to worker_id;
alter table WorkersOfMyCompany rename column wname to worker_name;

insert into WorkersOfMyCompany(worker_name,wsalary)values('Pokesh',8000000);
insert into WorkersOfMyCompany(worker_name,wsalary)values('Dinesh',40000);
insert into WorkersOfMyCompany(worker_name,wsalary)values('Gokul',60000);
insert into WorkersOfMyCompany(worker_name,wsalary)values('Rahul',50000);
insert into WorkersOfMyCompany(worker_name,wsalary)values('Selva',800000);
insert into WorkersOfMyCompany(worker_name,wsalary)values('Mano',80000);


select worker_name,wsalary,wsalary+(wsalary*0.5/100)as Salary,to_char(wjoindate,'day')as Day from WorkersOfMyCompany;

select * from WorkersOfMyCompany where worker_name like '%h';
select count(*) as Count from WorkersOfMyCompany where wsalary BETWEEN 30000 and 60000;


select * from WorkersOfMyCompany where worker_name like '____l';

select * from WorkersOfMyCompany where wsalary BETWEEN 30000 and 60000;

