create table salary(
Emp_id int generated by default as identity,
Emp_name varchar(30),
Emp_salary number(8),
Emp_Join_date timestamp default systimestamp ,
PRIMARY key(Emp_id));

insert into salary(Emp_name,Emp_salary) values('Saravana',40000);
select * from salary;

--select Emp_salary,Emp_salary desc from salary where Emp_salary>55000;
select * from(select Emp_name,Emp_salary,dense_rank() over(order by Emp_salary desc)as Top3 from salary) where Top3<=3;

select * from(select Emp_name,Emp_salary,dense_rank() over(order by Emp_salary)as lowest from salary)where lowest<=3;

select * from salary where Emp_name like 'S%a';

select Emp_name,row_number() over(order by Emp_name)as Odd from salary; 

select * from(select Emp_name,row_number() over(order by Emp_name)as Odd from salary) where mod(Odd,2)<>0;


