select * from products;

insert into products(prod_name)values('moulivakkam');
--it will print the 2nd value whenever the 1st value is there in table and it will print 3rd value whenver the 1st value is not in the table
select prod_name,decode (prod_name,'Porur','Chennai','Oor')as Decode from products;

--temprory table and sub query cration for using alay as
--it will print h wherever the value will be Pourur,and print n wherever the value is not chennai
select * from(select prod_name,decode (prod_name,'Porur','yes','No')as De from products)where De!='yes';

select * from(select prod_name as name,decode (prod_name,'Porur','yes','No')as De from products)where name='porur' and De='No';

--print odd number of pro_id with certain condition use mod while using condition
select * from products where mod(prod_id,2)!=0;

select * from products where 3=3;

select * from products where mod(cust_id,2)<>0;

--while using any function we must use over and inside the over we need to use orderby must
select prod_name,row_number() over(order by prod_name)as rown from products;

--if the prod_id is not number order it mixed value u can use this method
select * from(select prod_name,row_number() over(order by prod_name)as rown from products) where mod(rown,2)<>0;

--rownum is for limit
--row-number is assing value number  for each recodrs
 
--creating user name for each person 
create user pokesh identified by admin12;//this syntax is right but oracle is not allow this
grant CREATE SESSION to pokesh;//this is for create user and password
grant select on products to pokesh; //this is for give table access for that user table
grant insert on products to pokesh;
grant update on products to pokesh;
grant delete on products to pokesh;

create user Dinesh identified by admin12;//this syntax is right but oracle is not allow this
grant CREATE SESSION to Dinesh;//this is for create user and password
grant select on products to Dinesh; //this is for give table access for that user table
grant insert on products to Dinesh;
grant update on products to Dinesh;
grant delete on products to Dinesh;

--we can allow this syntax in this oracle with certain command
alter session set "_ORACLE_SCRIPT"=true;//this is for access previlage for that users

insert into products(prod_name) select prod_name from product2;
select * from products;

create table copy1(
prod_id int generated by default as identity,
prod_name varchar(30),
ent_dt TIMESTAMP default systimestamp
);
insert into copy1(prod_name) values('Dinesh');
select * from copy1;

create table costom11(
sale_id int generated by default as IDENTITY,
sale_name varchar(30),
ent_dt TIMESTAMP default systimestamp
);

select * from costom11;

grant select on costom11 to pokesh; //this is for give table access for that user table
grant insert on costom11 to pokesh;
grant update on costom11 to pokesh;
grant delete on costom11 to pokesh;


create user Malliga identified by malli;//this syntax is right but oracle is not allow this
grant CREATE SESSION to Malliga;
grant select on costom11 to Malliga; //this is for give table access for that user table
grant insert on costom11 to Malliga;
grant update on costom11 to Malliga;
grant delete on costom11 to Malliga;

create user Kalai identified by pokesh;
grant create session to Kalai;
grant select on products to Kalai;
grant insert on products to Kalai;
grant update on products to Kalai;
grant delete on products to Kalai; 