--sql data type
--1,number
--2,chatAt
--3,varcar
--4,date
--5,timrstamp
--6,vlob

--DDL in Sql
create table employees(
id number(3),
emp_name varchar(50),
emp_phone number(10),
ent_dt TIMESTAMP default systimestamp,
mod_dt TIMESTAMP,
PRIMARY KEY(id)
);

--desc is an describe methods you can see table is created by your given data types
--default value check go to table name and then click ctrl +click
alter table  employees modify id not null;
alter table employees drop(id);
alter table employees add id number GENERATED by DEFAULT AS IDENTITY;

alter TABLE employees add emp_address VARCHAR(200);

alter table employees add Position VARCHAR(100);
alter table employees MODIFY Position int;

desc employees;

--drop coloum here
alter table employees drop(Position); 

--to chenge the coloum name permanatly here
alter table employees rename COLUMN emp_address  to new_address ;
alter table employees rename COLUMN new_address  to emp_address ;

alter table employees MODIFY emp_phone NUMBER CHECK(emp_phone>0)NOT NULL;

--chenge the table name here
RENAME employees to Buddys;
select * from Buddys;
select * from employees;
rename Buddys to employees;

ALTER TABLE employees MODIFY mod_dt default systimestamp;

--if we want to delete the table you can use drop table (table name)
drop table employees;

--to show table that we created above
desc employees; 


--DML Changes in SQL
INSERT into employees(emp_name,emp_address,emp_phone) values('gokul','madhuravayal',928283);

select * from employees;

--select the value u need to show here by coloum name
select emp_name from employees;

--if u want to remove duplicates value u need to enter the one coloum value only
--distinct work when we use it in some specific coloum
select distinct (emp_name),id from employees;

--distinct is to remove duplicates values from the table while fetching values
select distinct (emp_name) from employees;

--you can set maltipule value by using the , where
update employees set emp_phone=6383532388,emp_name='Dinesh Values' where id=3;
 
-- the and operator need to satisfied two condition to show values
select * from employees where id=4 and emp_name='Mano';

-- the or operator need to satisfied any one condition to show values
select * from employees where emp_name='Pokesh' or emp_name='Mano';

select * from employees where emp_name in('Pokesh','Mano');

select * from employees where mod(id,2)!=0;

-- the and operator need to satisfied any one condition to show values
select * from employees where id=3 or emp_name='mano';
 
update employees set emp_phone=6383532388,emp_name='Pokesh Kumar',emp_address='chennai-mowlivakkam',mod_dt=systimestamp where id=25;

select * from employees;


DELETE employees where id=24;

delete employees where id=7;

--commit methods used to commit the queries here
commit;
ROLLBACK;

--truncate is used to delete all table data values 
truncate table employees;

commit;