create table copy1(
prod_id int generated by default as identity,
prod_name varchar(30),
age int
);

create table copy2(
prod_id int generated by default as identity,
prod_name varchar(30),
age int
);


--Create table that copy of another table
create table copydata as select * from products;

TRUNCATE table copy1;
drop TABLE copy1;
drop TABLE copy2;
select * from copy1;
select * from copy2;
desc copy1;
select * from products;
 
insert into copy1(prod_name,age) values('Kumar',23);
insert into copy2(prod_name,age) values('Kumar',23);

--insert all data to one table from another table
--Insert All Value To copydata from products  
insert into copydata(prod_id,prod_name) select prod_id,prod_name from products;
insert into copydata select * from products;
select * from copydata;

drop table copydata;
truncate table copydata; 

desc copydata;

insert into copydata(prod_name) select prod_name from products;

--Update all data 
--it will change all cust_id null value data's prod_name to Pokesh
update copydata set prod_name='Pokesh' where cust_id is null;
select * from copydata;

--Update all data using Dmmy Condition 1=1 or not null
update copydata set prod_name='Pokesh' where 1=1;


--it will delete all data from where cust_id is not null
delete from copydata where cust_id is  null;
 
select * from products;
 
--UNION (won’t duplicate with same column data values from 2 diff table)
select * from copy1 union select * from copy2;
select * from copy1;
select * from copy2;
--UNION ALL (accept duplicate with same column data values from 2 diff table)
select * from copy1 union all select * from copy2;

--Group by ,Order ,Join
--Group by
--Group by comes in the mind when we need to get count value by One Specific(sum,count,average,round)
--we use having in group by

--Order By
--Order By Used to Assign a specific coloum to order in  assending or decending order 

--Join
-- SQl Is an Rdbms(relational database managements system)
-- one table data related to another table data
-- w can join two table by using trainer_id from student table to trainer table trainer id 

--Views 
-- views will store a specific query values in views
-- we will get certain data by using views every time without writing query

select power(8,2) from dual;

with w as(
select prod_name as Pname from copydata
)select * from w where w.Pname='Usa'; 

select * from copydata where prod_name='Russia';

with N as(select * from copydata where prod_name='Russia')select * from N where N.ENT_DT is null;



commit;